### ISSUE TITLE
Geode update - all effects queue

### ISSUE THREAD

**Issue by MrS4turn** [WarpWorld/CCPack-PC-GeometryDash#2]
Geode updated to 4.0.1. After building with that version it seems effects queue/fail. Not seeing any helpful errors when sending effects.

Hopefully this helps https://github.com/geode-sdk/geode/blob/main/CHANGELOG.md

**Comment by MrS4turn** [comment]
Game in maintenance mode for now https://github.com/WarpWorld/crowd-control/commit/39dc382239cff7bcc5fe2e19a5888c38154684a5

**Comment by dtothefourth** [comment]
pushed an update to test

**Comment by MrS4turn** [comment]
issue was with effect test. fixed here: fca122ba19a965baf3a77244dce6c937ed38a3e7
